### ISSUE TITLE
problem:undefined method 'invoke_method'

### ISSUE THREAD

**Issue by lxmxhh** [taweili/renren#2]
Error msg:
Processing HomeController#index (for 127.0.0.1 at 2010-09-08 19:32:39) [GET]
NoMethodError (undefined method `invoke_method' for nil:NilClass):
  app/controllers/home_controller.rb:8:in`index'

home_controller.rb is like followes
class HomeController < ApplicationController

  before_filter :set_renren_session
  helper_method :renren_session

  def index 
    @user = renren_session.invoke_method("renren.users.getInfo",..............)
.........

thanks a lot

**Comment by flyerhzm** [comment]
You should login first, then use the renren_session

**Comment by lxmxhh** [comment]
how can i login? i mean i want to login on my local server with or without using connect.

**Comment by flyerhzm** [comment]
with connect, see here http://wiki.github.com/taweili/renren/renren-connect
without connect, you should ask taweili

**Comment by lxmxhh** [comment]
ok, i figure out the login issue. thank you
